$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries: []
dictionaryDefinitions: []
enableFiletypes:
  - json
  - makefile
  - markdown
  - plaintext
  - shellscript
  - text
ignorePaths:
  - .gitignore
  - cspell.config.yaml
  - KeyMaps/**
  - TrackTemplates/**
ignoreWords: []
import:
  - ../cspell.config.yaml
version: "0.2"
words:
  - Cockos
  - FEETS
  - Floortom
  - Oneshot
  - Racktom
  - Rimshot
  - Sidestick
