# https://pre-commit.com/index.html#adding-pre-commit-plugins-to-your-project
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker

  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace

  # https://github.com/streetsidesoftware/cspell-cli#setup-pre-commit-hook
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.3.0
    hooks:
      - id: cspell

  # https://github.com/DavidAnson/markdownlint-cli2#pre-commit
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2

  # https://github.com/tcort/markdown-link-check#run-as-a-pre-commit-hook
  # - repo: https://github.com/tcort/markdown-link-check
  #   rev: v3.11.2
  #   hooks:
  #     - id: markdown-link-check
  #       args: [--config, .markdown-link-check.json, -q]
