$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries: []
dictionaryDefinitions: []
enableFiletypes:
  - github-actions-workflow
  - json
  - makefile
  - markdown
  - plaintext
  - shellscript
  - text
  - yaml
ignorePaths:
  - .envrc.local
  - .gitignore
  - cspell.config.yaml
ignoreWords: []
import: []
version: "0.2"
words:
  - automount
  - checkmake
  - chsh
  - direnv
  - kkrull
  - Krull
  - minphony
  - shellcheck
