alias gloga='LESS=$LESS"S" git log --oneline --graph --decorate --all'
alias glso='git ls-files -o --exclude=*.iml --exclude=.idea'
alias splitpath="tr : '\n'"
alias tmux-source='tmux source-file'
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])"'
