#. ==dotfiles/tmux==

.PHONY: default
default: all

include ../make.d/help.mk

## Project

## Sources

.PHONY: debug-sources
debug-sources:
	$(info Sources:)
	@:

## Artifacts

## Paths

.PHONY: debug-paths
debug-paths:
	$(info Paths:)
	@:

## Programs

#. DEVELOPMENT ENVIRONMENT TARGETS

.PHONY: install-tools
install-tools:
	@:

#. STANDARD TARGETS

.PHONY: all
all:
	@:

.PHONY: clean
clean:
	@:

# TODO KDK: Use `install` to install symlinks in $XDG_CONFIG_HOME or $HOME/.config
.PHONY: install
install: #> Install configuration
	@:

.PHONY: test
test:
	@:

# TODO KDK: Unlink
.PHONY: uninstall
uninstall: #> Uninstall configuration
	@:

#. SUPPORT TARGETS

.PHONY: debug
.NOTPARALLEL: debug
debug: _debug-prefix debug-paths debug-sources #> Show debugging information
	@:

.PHONY: _debug-prefix
_debug-prefix:
	$(info ==dotfiles/tmux==)
	@:
