$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
dictionaries: []
dictionaryDefinitions: []
enableFiletypes:
  - makefile
  - markdown
  - plaintext
  - shellscript
  - text
ignorePaths:
  - .gitignore
  - .zshrc.d/rn/alias.zsh
  - cspell.config.yaml
ignoreWords: []
import:
  - ../cspell.config.yaml
version: "0.2"
words:
  - argcomplete
  - AUTOUPDATE
  - chruby
  - direnv
  - fpath
  - GOPATH
  - homebrewdep
  - jenv
  - libexec
  - linuxbrew
  - Makefiles
  - mybatis
  - pipx
  - pyenv
  - robbyrussell
  - rustup
  - SDKMAN
  - sfdx
  - shellenv
  - sode
  - venvs
  - ZDOTDIR
