name: Repository
description: CI running at the repository root

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  python_version: '3.13.2'

permissions:
  contents: read

jobs:
  pre-commit-run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - run: python --version
      - uses: pre-commit/action@v3.0.1
